// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnwczrpotbjjxexjhibg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhud2N6cnBvdGJqanhleGpoaWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDIwMDgsImV4cCI6MjA2NTU3ODAwOH0.Tti4taGbxUghaD-htRUvI-8uZxJjFtt8-QuCKPhojiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);